apiVersion: v1
kind: Secret
metadata:
  name: docdb-credentials
type: Opaque
stringData:
  uri: "mongodb://username:password@sockshop-docdb-cluster.cluster-cadqyg8as50n.us-east-1.docdb.amazonaws.com:27017/data?tls=true&replicaSet=rs0&retryWrites=false"