apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
  AWS_DEFAULT_REGION: {{ .Values.aws.region | b64enc }}
